### ISSUE TITLE
i18n/l10n support

### ISSUE THREAD

**Issue by neutronstein** [mishka-group/guarded_struct#10]
Having ability to translate error messages would be amazing. Can you please consider this? Thanks

**Comment by shahryarjb** [comment]
Hello @neutronstein ,
I hope you're doing well. 😊 Your suggestion is definitely noted, and I'll do my best to implement it in future releases. However, I've been quite busy recently with the [Mishka Chelekom](https://github.com/mishka-group/mishka_chelekom) project. 

Please give me a bit of time to release an update for that, and I'll make sure to research and work on implementing multilingual support here as well.

If it's something urgent, I'd be more than happy to review a pull request from you! 🚀

Thank you so much for your support and for sharing your feedback and suggestions—they truly help improve the project. 🙏

Best regards,
Shahryar

**Comment by shahryarjb** [comment]
Hello, dear @neutronstein . I’ve added this feature, and I hope you find it useful.
If you’re using this library in a production project, please consider supporting us even **a coffee**.
Wishing you all the best!

- Doc: https://hexdocs.pm/guarded_struct/GuardedStruct.Messages.html
- Code: https://github.com/mishka-group/guarded_struct/blob/master/lib/messages.ex
